version: '3'
services:
  auth:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    container_name: auth
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - database
    restart: on-failure
    environment:
      - POSTGRESQL_HOST=database
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=root
      - POSTGRESQL_PASSWORD=root
      - APP_PORT=8080
      - FRONTEND_URL=http://localhost:3000
      - ENCRYPT_PASSWORD=mysecretpassword
      - LOAD_DEFAULT_DATA=true
      - SECRET_KEY_TOKEN=mysecretkeypassword
    networks:
      - bridge
    ports:
      - "8080:8080"
  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    container_name: database
    ports:
      - "25432:5432"
    networks:
      - bridge
  proxy:
      image: nginx
      ports:
          - 18080:80
      depends_on:
        - auth
      restart: always
      healthcheck:
        test: curl --fail http://auth:8080/healthcheck || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
          - bridge
networks:
  bridge:
    driver: bridge
